### ISSUE TITLE
Perform dark correction

### ISSUE THREAD

**Issue by mgalloy** [NCAR/chromag-pipeline#10]
The requirements for the dark to be used for dark subtraction:

- average darks together by exposure time, camera gain, and camera bit depth, and be within a tolerance of camera temperature (`CAM_T`)

#### Questions

- [x] How do I tell if a file is a dark? *`DATATYPE` is "Calibration" and `OBJECT` is "Dark".*
- [x] Is there anything else that must match between the darks and a science image besides exposure time? *Exposure time, camera gain, camera bit depth, and camera temperature (I assume `CAM_T`)*

#### Tasks

- [x] group/average darks by exposure time, camera gain, and camera bit depth
- [x] save darks in calibration netCDF file
- [x] retrieve matching dark by exposure time, camera gain, and camera bit depth
- [x] dark subtraction
- [x] record metadata in FITS header about dark application
